### ISSUE TITLE
Images not delete

### ISSUE THREAD

**Issue by tgb20** [tgb20/ImageToSkin#1]
The uploaded images by users and the generated skins should be deleted. This will preserve server space and prevent issues with any images that are uploaded.

I think this should be around 3-4 minutes after generating the skin.

**Comment by akshatsinghania** [comment]
can i be assigned to this issue?

**Comment by tgb20** [comment]
If you want to work on it sure!

**Comment by akshatsinghania** [comment]
ok thanks i will start working on it

**Comment by akshatsinghania** [comment]
i forgot about this lol , ill start working

**Comment by tgb20** [comment]
I am rewriting ImageToSkin to run client side with React so this will no longer be an issue.
